REVOKE ALL ON SCHEMA grit FROM fphs;
GRANT ALL ON SCHEMA grit TO fphs;
GRANT USAGE ON SCHEMA grit TO fphsadm;
GRANT USAGE ON SCHEMA grit TO fphsusr;
GRANT USAGE ON SCHEMA grit TO fphsetl;


GRANT ALL ON ALL TABLES IN SCHEMA grit TO fphs;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA grit TO fphsusr;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA grit TO fphsetl;
GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON ALL TABLES IN SCHEMA grit TO fphsadm;

GRANT ALL ON ALL SEQUENCES IN SCHEMA grit TO fphs;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA grit TO fphsusr;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA grit TO fphsetl;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA grit TO fphsadm;


DO
$body$
BEGIN

IF EXISTS (
   SELECT *
   FROM   pg_catalog.pg_roles
   WHERE  rolname = 'fphsrailsapp') THEN

   GRANT USAGE ON SCHEMA grit TO fphsrailsapp;
   GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA grit TO fphsrailsapp;
   GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA grit TO fphsrailsapp;
END IF;


END
$body$;
