require 'active_record/migration/app_generator'
class UpdateIpaMedicalDetailsQghrzh < ActiveRecord::Migration[5.2]
  include ActiveRecord::Migration::AppGenerator

  def change
    self.schema = 'ipa_ops'
    self.table_name = 'ipa_medical_details'
    self.fields = %i[form_version convulsion_or_seizure_blank_yes_no_dont_know convulsion_or_seizure_details sleep_disorder_blank_yes_no_dont_know sleep_disorder_details sleep_apnea_device_no_yes number_of_nights_sleep_apnea_device sleep_apnea_travel_with_device_yes_no sleep_apnea_device_details chronic_pain_blank_yes_no chronic_pain_details chronic_pain_meds_blank_yes_no_dont_know chronic_pain_meds_details hypertension_diagnosis_blank_yes_no_dont_know hypertension_medications_blank_yes_no hypertension_diagnosis_details diabetes_diagnosis_blank_yes_no_dont_know diabetes_medications_blank_yes_no diabetes_diagnosis_details hemophilia_blank_yes_no_dont_know hemophilia_details high_cholesterol_diagnosis_blank_yes_no_dont_know high_cholesterol_medications_blank_yes_no high_cholesterol_diagnosis_details caridiac_pacemaker_blank_yes_no_dont_know caridiac_pacemaker_details other_heart_conditions_blank_yes_no_dont_know other_heart_conditions_details memory_problems_blank_yes_no_dont_know memory_problems_details mental_health_conditions_blank_yes_no_dont_know mental_health_conditions_details mental_health_help_blank_yes_no_dont_know mental_health_help_details neurological_problems_blank_yes_no_dont_know neurological_problems_details past_mri_yes_no_dont_know past_mri_details metal_implants_blank_yes_no_dont_know metal_implants_details metal_implants_mri_approval_details radiation_blank_yes_no select_radiation_type radiation_details dietary_restrictions_blank_yes_no_dont_know dietary_restrictions_details]
    self.table_comment = ''
    self.fields_comments = {}


    self.prev_fields = %i[convulsion_or_seizure_blank_yes_no_dont_know convulsion_or_seizure_details sleep_disorder_blank_yes_no_dont_know sleep_disorder_details sleep_apnea_device_no_yes sleep_apnea_device_details chronic_pain_blank_yes_no chronic_pain_details chronic_pain_meds_blank_yes_no_dont_know chronic_pain_meds_details hypertension_diagnosis_blank_yes_no_dont_know hypertension_medications_blank_yes_no hypertension_diagnosis_details diabetes_diagnosis_blank_yes_no_dont_know diabetes_medications_blank_yes_no diabetes_diagnosis_details hemophilia_blank_yes_no_dont_know hemophilia_details high_cholesterol_diagnosis_blank_yes_no_dont_know high_cholesterol_medications_blank_yes_no high_cholesterol_diagnosis_details caridiac_pacemaker_blank_yes_no_dont_know caridiac_pacemaker_details other_heart_conditions_blank_yes_no_dont_know other_heart_conditions_details memory_problems_blank_yes_no_dont_know memory_problems_details mental_health_conditions_blank_yes_no_dont_know mental_health_conditions_details mental_health_help_blank_yes_no_dont_know mental_health_help_details neurological_problems_blank_yes_no_dont_know neurological_problems_details past_mri_yes_no_dont_know past_mri_details dietary_restrictions_blank_yes_no_dont_know dietary_restrictions_details metal_implants_blank_yes_no_dont_know metal_implants_details metal_implants_mri_approval_details radiation_details radiation_blank_yes_no]
    # added: ["form_version", "number_of_nights_sleep_apnea_device", "sleep_apnea_travel_with_device_yes_no", "select_radiation_type"]
    # removed: []
    
    
    update_fields

    create_dynamic_model_trigger
  end
end
