_definitions:


  ####
  # Boilerplace for notifying roles
  # Directly call in a trigger like:
  #
  # save_trigger:
  #   on_create:
  #     notify: &notify_hms_ps
  #
  ####

  ###########

  # Creator
  notify_discussion_creator_option: &notify_discussion_creator
    <<: *notify_email_default
    users:
      referring_record:
        user_id: return_value

  # Creator SMS
  notify_discussion_creator_option_sms: &notify_discussion_creator_sms
    <<: *notify_sms_default
    users:
      referring_record:
        user_id: return_value

  ###########

  # Phone Screen Interviewer
  notify_ps_int: &notify_ps_int
    <<: *notify_email_default
    users:
      dynamic_model__ipa_ps_initial_screenings:
        user_id: return_value

  notify_ps_int_sms: &notify_ps_int_sms
    <<: *notify_sms_default
    users:
      dynamic_model__ipa_ps_initial_screenings:
        user_id: return_value

  ###########

  # Navigators
  notify_navigators: &notify_navigators
    <<: *notify_email_default
    role: email - navigator

  notify_navigators_sms: &notify_navigators_sms
    <<: *notify_sms_default
    role: sms - navigator

  ###########

  # Clinical Research Coordinator
  notify_crc: &notify_crc
    <<: *notify_email_default
    role: email - crc

  notify_crc_sms: &notify_crc_sms
    <<: *notify_sms_default
    role: sms - crc

  ###########

  # Med Nav
  notify_med_nav: &notify_med_nav
    <<: *notify_email_default
    role: email - mednav

  notify_med_nav_sms: &notify_med_nav_sms
    <<: *notify_sms_default
    role: sms - mednav

  ###########

  # TMS
  notify_tms: &notify_tms
    <<: *notify_email_default
    role: email - tms

  notify_tms_sms: &notify_tms_sms
    <<: *notify_sms_default
    role: sms - tms

  ###########

  # PI
  notify_pi: &notify_pi
    <<: *notify_email_default
    role: email - pi

  # PI SMS
  notify_pi_sms: &notify_pi_sms
    <<: *notify_sms_default
    role: sms - pi

  ###########

  # HMS Admin
  notify_hms_admin: &notify_hms_admin
    <<: *notify_email_default
    role: email - hms admin

  # HMS Admin SMS
  notify_hms_admin_sms: &notify_hms_admin_sms
    <<: *notify_sms_default
    role: sms - hms admin
