_definitions:


  ####
  # Base Boilerplace for notifying roles
  # Add role or users attributes
  # Override the subject: and if: structures to refine operation
  ####

  # Default email - just add roles or users
  notify_email_default: &notify_email_default
    type: email
    layout_template: ipa notification layout
    content_template: ipa notification message
    role:
    subject: "IPA App: Notification message"
    extra_substitutions:
      reason: ''
      extra_text: ''
      panel_tab: none


  # Default SMS - just add roles or users
  notify_sms_default: &notify_sms_default
    type: sms
    layout_template: standard sms layout
    content_template: ipa sms notification
    role:
    subject: "IPA Notification"
