_definitions:

  ref_filestore_container: &ref_filestore_container
    nfs_store__manage__container: &ref_nfs_store__manage__container
      from: this
      add: one_to_this
      view_as:
        edit: hide
        show: filestore
        new: not_embedded
      creatable_if:
        never: true

  save_trigger:
    on_create_filestore_container: &create_filestore_container
      create_filestore_container:
        name: general files
        label: General Files
        create_with_role: nfs_store group 600



  files_activity: &files_activity
    label: Supporting Files
    fields:
      - notes

    caption_before:
      notes: Describe the files in this container. Individual files can also be given a title and description in the file classifications.

    creatable_if:
      <<: *enabled_if

    editable_if:
      <<: *enabled_if

    save_trigger:
      on_create:
        <<: *create_filestore_container

    references:
      nfs_store__manage__container:
        <<: *ref_nfs_store__manage__container
