# NOTE:
# It is essential to load the following libraries before this one:
#  ipa notification_base
#  ipa notify_roles
#  ipa discussions



_definitions:

  ####
  # Handle options for generic contact forms, allowing a
  # drop-down to select which role or user is notified
  # At least one of these should be set for each entry in
  # *role_selection_options
  # which is defined in the Discussions activity log definition
  ####


  notify_options: &notify_options

    - <<: *notify_discussion_creator
    - <<: *notify_discussion_creator_sms

    ##############

    - <<: *notify_ps_int
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: phone screen interviewer
              condition: '= ANY'

    - <<: *notify_ps_int_sms
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: phone screen interviewer
              condition: '= ANY'

    ##############

    - <<: *notify_navigators
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: navigators
              condition: '= ANY'

    - <<: *notify_navigators_sms
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: navigators
              condition: '= ANY'

    ##############

    - <<: *notify_crc
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: clinical research coordinator
              condition: '= ANY'

    - <<: *notify_crc_sms
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: clinical research coordinator
              condition: '= ANY'

    ##############

    - <<: *notify_med_nav
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: med nav
              condition: '= ANY'

    - <<: *notify_med_nav_sms
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: med nav
              condition: '= ANY'

    ##############

    - <<: *notify_tms
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: tms
              condition: '= ANY'

    - <<: *notify_tms_sms
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: tms
              condition: '= ANY'

    ##############

    - <<: *notify_pi
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: pi
              condition: '= ANY'


    - <<: *notify_pi_sms
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: pi
              condition: '= ANY'

    ##############

    - <<: *notify_hms_admin
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: hms admins
              condition: '= ANY'


    - <<: *notify_hms_admin_sms
      if:
        all:
          referring_record:
            tag_select_contact_role:
              value: hms admins
              condition: '= ANY'

    ##############

########################################
# Done handling role selection
########################################


####
# Defaults for the form for setting up a new discussion
# Nothing should require editing in this block
####

  setup_discussion: &setup_discussion
    fields:
      - notes
      - tag_select_contact_role
      - prev_activity_type

    field_options: &start_discussion_field_options

      notes:
        edit_as:
          field_type: subject

      prev_activity_type:
        edit_as:
          field_type: fixed_type
        value:
          this:
            extra_log_type: return_value


    show_if:
      prev_activity_type:
        never: true

    valid_if:
      on_save:
        not_any:
          this:
            subject: ''

    labels:
      tag_select_contact_role: notify role

    caption_before: &setup_discussion_caption_before
      all_fields: |
        Setup a discussion to securely contact the selected roles.

        Messages are visible, and notifications sent to only the users with the
        selected roles (and the creator of the discussion: {{user_email}}).
        To change this visibility, and future notifications, edit this discussion before sending new messages.

      notes:
        edit_caption: |
          Enter subject of the discussion

          *Do not enter any PII or PHI in this field,
          since it will be included in notification emails*
        show_caption: Subject
      tag_select_contact_role: Roles to be included


    references:
      - activity_log__ipa_assignment_ipa_discussion:
          label: New Message
          from: this
          add: many
          prevent_disable: true
          add_with:
            extra_log_type:
              this:
                prev_activity_type: return_value
            prev_activity_type:
              this:
                extra_log_type: return_value
          filter_by:
            extra_log_type:
              this:
                prev_activity_type: return_value

    editable_if:
      <<: *enabled_if

    creatable_if:
      <<: *enabled_if


  ####
  # Contact defaults for all generic contact forms
  ####
  discussion_message_defaults: &discussion_message_defaults
    fields:
      - notes
      - prev_activity_type

    field_options:
      prev_activity_type:
        edit_as:
          field_type: fixed_type

    caption_before: &contact_caption_before
      submit: After clicking <i>Send</i> a notification message will be sent to the roles
        selected in the discussion setup.

      notes: |
        **Message:** The message text is not sent by email, so can include PHI.

    show_if:
      prev_activity_type:
        never: true

    view_options:
      data_attribute:
        - notes
      hide_unless_creatable: true

    showable_if:
      <<: *enabled_if
      all:
        this:
          prev_activity_type: ''


    editable_if:
      never: true

    creatable_if:
      never: true


    save_action:
      label: Send

    save_trigger:
      on_create:
        notify: *notify_options
        update_reference:
          ref:

            first:
              all:
                referring_record:
                  update: return_result

            with:
              updated_at: now()
