Metrics/LineLength:
  Enabled: true
  Max: 120
  Include:
    - 'app/**/*'
    # - 'spec/**/*'

# This includes concerns like class_methods blocks
Metrics/BlockLength:
  Enabled: true
  Max: 200
  Include:
    - 'app/**/*'
    # - 'spec/**/*'

Metrics/ModuleLength:
  Enabled: true
  Max: 800
  Include:
    - 'app/**/*'

Metrics/MethodLength:
  Enabled: true
  Max: 50
  Include:
    - 'app/**/*'
    # - 'spec/**/*'

Metrics/ClassLength:
  Enabled: true
  Max: 800
  Include:
    - 'app/**/*'

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 30
  Include:
    - 'app/**/*'

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 30
  Include:
    - 'app/**/*'

Naming/ConstantName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false


Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
