set search_path=ml_app;
\i db/app_specific/ipa/create_activity_log_adverse_events_table.sql
\i db/app_specific/ipa/create_activity_log_inex_checklist_table.sql
\i db/app_specific/ipa/create_activity_log_ipa_assignment_phone_screens_table.sql
\i db/app_specific/ipa/create_activity_log_ipa_assignments.sql
\i db/app_specific/ipa/create_activity_log_ipa_protocol_deviations_table.sql
\i db/app_specific/ipa/create_activity_log_navigation_table.sql
\i db/app_specific/ipa/create_activity_log_post_visit_table.sql
\i db/app_specific/ipa/create_emergency_contacts.sql
\i db/app_specific/ipa/create_ipa_adverse_events_table.sql
\i db/app_specific/ipa/create_ipa_appointment_table.sql
\i db/app_specific/ipa/create_ipa_consent_mailings.sql
\i db/app_specific/ipa/create_ipa_hotel_table.sql
\i db/app_specific/ipa/create_ipa_inex_checklist_table.sql
\i db/app_specific/ipa/create_ipa_init_screening_table.sql
\i db/app_specific/ipa/create_ipa_mris_table.sql
\i db/app_specific/ipa/create_ipa_payment_table.sql
\i db/app_specific/ipa/create_ipa_protocol_deviations_table.sql
\i db/app_specific/ipa/create_ipa_ps_football_experience_table.sql
\i db/app_specific/ipa/create_ipa_ps_health_table.sql
\i db/app_specific/ipa/create_ipa_ps_init_screening_table.sql
\i db/app_specific/ipa/create_ipa_ps_size_table.sql
\i db/app_specific/ipa/create_ipa_ps_tmocas_table.sql
\i db/app_specific/ipa/create_ipa_screenings_table.sql
\i db/app_specific/ipa/create_ipa_survey_table.sql
\i db/app_specific/ipa/create_ipa_screening_survey_activity_log_table.sql
\i db/app_specific/ipa/create_ipa_sleeps_table.sql
\i db/app_specific/ipa/create_ipa_tms_tests_table.sql
\i db/app_specific/ipa/create_ipa_transportation_table.sql
\i db/app_specific/ipa/create_ipa_withdrawals_table.sql
\i db/app_specific/ipa/post_create_alter_withdrawals_table.sql
\i db/app_specific/ipa/create_minor_deviations_activity_log.sql
\i db/app_specific/ipa/create_mrn_external_identifier.sql
\i db/app_specific/ipa/prep_inex_checklist_from_ps.sql
\i db/app_specific/ipa/trigger_new_screening_schedule.sql
\i db/app_specific/ipa/trigger_screening_follow_up.sql
