-- SQL run by sync_subject_data.sh
-- Running this SQL script independently does not make sense
set search_path=ml_app, ipa_ops;


CREATE TEMPORARY TABLE temp_adl_screeners AS ( SELECT * FROM ipa_ops.adl_screener_data WHERE record_id IS NULL );

ALTER TABLE temp_adl_screeners ADD COLUMN ipa_id BIGINT, ADD COLUMN master_id INTEGER, ADD COLUMN status varchar, ADD COLUMN to_master_id INTEGER;

\copy temp_adl_screeners  from $IPA_ADL_SCREENERS_FILE with (header true, format csv)

UPDATE temp_adl_screeners SET status = 'failed';
UPDATE temp_adl_screeners SET to_master_id = (select DISTINCT master_id from ipa_ops.ipa_assignments ipa WHERE ipa.ipa_id = temp_adl_screeners.ipa_id limit 1), status = 'completed';

INSERT INTO adl_screener_data
(
  record_id	,
  adcs_npiq_timestamp	,
  adlnpi_consent___agree	,
  informant	,
  adl_eat	,
  adl_walk	,
  adl_toilet	,
  adl_bath	,
  adl_groom	,
  adl_dressa	,
  adl_dressa_perf	,
  adl_dressb	,
  adl_phone	,
  adl_phone_perf	,
  adl_tv	,
  adl_tva	,
  adl_tvb	,
  adl_tvc	,
  adl_attnconvo	,
  adl_attnconvo_part	,
  adl_dishes	,
  adl_dishes_perf	,
  adl_belong	,
  adl_belong_perf	,
  adl_beverage	,
  adl_beverage_perf	,
  adl_snack	,
  adl_snack_prep	,
  adl_garbage	,
  adl_garbage_perf	,
  adl_travel	,
  adl_travel_perf	,
  adl_shop	,
  adl_shop_select	,
  adl_shop_pay	,
  adl_appt	,
  adl_appt_aware	,
  institutionalized___1	,
  adl_alone	,
  adl_alone_15m	,
  adl_alone_gt1hr	,
  adl_alone_lt1hr	,
  adl_currev	,
  adl_currev_tv	,
  adl_currev_outhome	,
  adl_currev_inhome	,
  adl_read	,
  adl_read_lt1hr	,
  adl_read_gt1hr	,
  adl_write	,
  adl_write_complex	,
  adl_hob	,
  adl_hobls___gam	,
  adl_hobls___bing	,
  adl_hobls___instr	,
  adl_hobls___read	,
  adl_hobls___tenn	,
  adl_hobls___cword	,
  adl_hobls___knit	,
  adl_hobls___gard	,
  adl_hobls___wshop	,
  adl_hobls___art	,
  adl_hobls___sew	,
  adl_hobls___golf	,
  adl_hobls___fish	,
  adl_hobls___oth	,
  adl_hobls_oth	,
  adl_hobdc___1	,
  adl_hob_perf	,
  adl_appl	,
  adl_applls___wash	,
  adl_applls___dish	,
  adl_applls___range	,
  adl_applls___dry	,
  adl_applls___toast	,
  adl_applls___micro	,
  adl_applls___vac	,
  adl_applls___toven	,
  adl_applls___fproc	,
  adl_applls___oth	,
  adl_applls_oth	,
  adl_appl_perf	,
  adl_comm	,

  npi_infor,
  npi_inforsp,
  npi_delus,
  npi_delussev,
  npi_hallu,
  npi_hallusev,
  npi_agita,
  npi_agitasev,
  npi_depre,
  npi_depresev,
  npi_anxie,
  npi_anxiesev,
  npi_elati,
  npi_elatisev,
  npi_apath,
  npi_apathsev,
  npi_disin,
  npi_disinsev,
  npi_irrit,
  npi_irritsev,
  npi_motor,
  npi_motorsev,
  npi_night,
  npi_nightsev,
  npi_appet,
  npi_appetsev,
  adcs_npiq_complete,

  redcap_survey_identifier
)
  SELECT
    record_id	,
    adcs_npiq_timestamp	,
    adlnpi_consent___agree	,
    informant	,
    adl_eat	,
    adl_walk	,
    adl_toilet	,
    adl_bath	,
    adl_groom	,
    adl_dressa	,
    adl_dressa_perf	,
    adl_dressb	,
    adl_phone	,
    adl_phone_perf	,
    adl_tv	,
    adl_tva	,
    adl_tvb	,
    adl_tvc	,
    adl_attnconvo	,
    adl_attnconvo_part	,
    adl_dishes	,
    adl_dishes_perf	,
    adl_belong	,
    adl_belong_perf	,
    adl_beverage	,
    adl_beverage_perf	,
    adl_snack	,
    adl_snack_prep	,
    adl_garbage	,
    adl_garbage_perf	,
    adl_travel	,
    adl_travel_perf	,
    adl_shop	,
    adl_shop_select	,
    adl_shop_pay	,
    adl_appt	,
    adl_appt_aware	,
    institutionalized___1	,
    adl_alone	,
    adl_alone_15m	,
    adl_alone_gt1hr	,
    adl_alone_lt1hr	,
    adl_currev	,
    adl_currev_tv	,
    adl_currev_outhome	,
    adl_currev_inhome	,
    adl_read	,
    adl_read_lt1hr	,
    adl_read_gt1hr	,
    adl_write	,
    adl_write_complex	,
    adl_hob	,
    adl_hobls___gam	,
    adl_hobls___bing	,
    adl_hobls___instr	,
    adl_hobls___read	,
    adl_hobls___tenn	,
    adl_hobls___cword	,
    adl_hobls___knit	,
    adl_hobls___gard	,
    adl_hobls___wshop	,
    adl_hobls___art	,
    adl_hobls___sew	,
    adl_hobls___golf	,
    adl_hobls___fish	,
    adl_hobls___oth	,
    adl_hobls_oth	,
    adl_hobdc___1	,
    adl_hob_perf	,
    adl_appl	,
    adl_applls___wash	,
    adl_applls___dish	,
    adl_applls___range	,
    adl_applls___dry	,
    adl_applls___toast	,
    adl_applls___micro	,
    adl_applls___vac	,
    adl_applls___toven	,
    adl_applls___fproc	,
    adl_applls___oth	,
    adl_applls_oth	,
    adl_appl_perf	,
    adl_comm	,

    npi_infor,
    npi_inforsp,
    npi_delus,
    npi_delussev,
    npi_hallu,
    npi_hallusev,
    npi_agita,
    npi_agitasev,
    npi_depre,
    npi_depresev,
    npi_anxie,
    npi_anxiesev,
    npi_elati,
    npi_elatisev,
    npi_apath,
    npi_apathsev,
    npi_disin,
    npi_disinsev,
    npi_irrit,
    npi_irritsev,
    npi_motor,
    npi_motorsev,
    npi_night,
    npi_nightsev,
    npi_appet,
    npi_appetsev,
    adcs_npiq_complete,

    redcap_survey_identifier
  FROM temp_adl_screeners;

-- Verify the insert worked ok
SELECT DISTINCT temp_adl_screeners.master_id, temp_adl_screeners.ipa_id, status, to_master_id FROM temp_adl_screeners INNER JOIN ipa_adl_informant_screeners ON ipa_adl_informant_screeners.master_id = to_master_id;

\copy (SELECT DISTINCT temp_adl_screeners.master_id, temp_adl_screeners.ipa_id, status, to_master_id FROM temp_adl_screeners INNER JOIN ipa_adl_informant_screeners ON ipa_adl_informant_screeners.master_id = to_master_id) TO $IPA_ASSIGNMENTS_RESULTS_FILE WITH (format csv, header true);
