REVOKE ALL ON SCHEMA q1 FROM fphs;
GRANT ALL ON SCHEMA q1 TO fphs;
GRANT USAGE ON SCHEMA q1 TO fphsadm;
GRANT USAGE ON SCHEMA q1 TO fphsusr;
GRANT USAGE ON SCHEMA q1 TO fphsetl;


GRANT ALL ON ALL TABLES IN SCHEMA q1 TO fphs;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA q1 TO fphsusr;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA q1 TO fphsetl;
GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON ALL TABLES IN SCHEMA q1 TO fphsadm;

GRANT ALL ON ALL SEQUENCES IN SCHEMA q1 TO fphs;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA q1 TO fphsusr;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA q1 TO fphsetl;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA q1 TO fphsadm;


DO
$body$
BEGIN

IF EXISTS (
   SELECT *
   FROM   pg_catalog.pg_roles
   WHERE  rolname = 'fphsrailsapp') THEN

   GRANT USAGE ON SCHEMA q1 TO fphsrailsapp;
   GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA q1 TO fphsrailsapp;
   GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA q1 TO fphsrailsapp;
END IF;


END
$body$;
