# Credentials file only used for test environment.
# Do not use for other environments

redcap:
  projects:
    - name: q2_demo
      api_key: 5916B33DA67D46FBDCBF95B85B54A893
      server_url: https://redcap.fphs.harvard.edu/api/

    - name: metadata
      api_key: F3C1DDA3B6799BBE29866981C68107E1
      server_url: https://redcapdemo.vanderbilt.edu/api/
