set search_path=ipa_ops;

CREATE TABLE ipa_adl_informant_screeners (
          id integer NOT NULL,
          master_id integer,
          select_regarding_eating varchar,
          select_regarding_walking varchar,
          select_regarding_bowel_and_bladder varchar,
          select_regarding_bathing varchar,
          select_regarding_grooming varchar,
          select_regarding_dressing varchar,
          select_regarding_dressing_performance varchar,
          select_regarding_getting_dressed varchar,
          used_telephone_yes_no_dont_know varchar,
          select_telephone_performance varchar,
          watched_tv_yes_no_dont_know varchar,
          selected_programs_yes_no_dont_know varchar,
          talk_about_content_during_yes_no_dont_know varchar,
          talk_about_content_after_yes_no_dont_know varchar,
          pay_attention_to_conversation_yes_no_dont_know varchar,
          select_degree_of_participation varchar,
          clear_dishes_yes_no_dont_know varchar,
          select_clear_dishes_performance varchar,
          find_personal_belongings_yes_no_dont_know varchar,
          select_find_personal_belongings_performance varchar,
          obtain_beverage_yes_no_dont_know varchar,
          select_obtain_beverage_performance varchar,
          make_meal_yes_no_dont_know varchar,
          select_make_meal_performance varchar,
          dispose_of_garbage_yes_no_dont_know varchar,
          select_dispose_of_garbage_performance varchar,
          get_around_outside_yes_no_dont_know varchar,
          select_get_around_outside_performance varchar,
          go_shopping_yes_no_dont_know varchar,
          select_go_shopping_performance varchar,
          pay_for_items_yes_no_dont_know varchar,
          keep_appointments_yes_no_dont_know varchar,
          select_keep_appointments_performance varchar,
          left_on_own_yes_no_dont_know varchar,
          away_from_home_yes_no_dont_know varchar,
          at_home_more_than_hour_yes_no_dont_know varchar,
          at_home_less_than_hour_yes_no_dont_know varchar,
          talk_about_current_events_yes_no_dont_know varchar,
          did_not_take_part_in_yes_no_dont_know varchar,
          took_part_in_outside_home_yes_no_dont_know varchar,
          took_part_in_at_home_yes_no_dont_know varchar,
          read_yes_no_dont_know varchar,
          talk_about_reading_shortly_after_yes_no_dont_know varchar,
          talk_about_reading_later_yes_no_dont_know varchar,
          write_yes_no_dont_know varchar,
          select_write_performance varchar,
          pastime_yes_no_dont_know varchar,
          multi_select_pastimes varchar,
          pastime_other varchar,
          pastimes_only_at_daycare_no_yes varchar,
          select_pastimes_only_at_daycare_performance varchar,
          use_household_appliance_yes_no_dont_know varchar,
          multi_select_household_appliances varchar,
          household_appliance_other varchar,
          select_household_appliance_performance varchar,
          user_id integer,
          created_at timestamp without time zone NOT NULL,
          updated_at timestamp without time zone NOT NULL
      );

