REVOKE ALL ON SCHEMA testmybrain FROM fphs;
GRANT ALL ON SCHEMA testmybrain TO fphs;
GRANT USAGE ON SCHEMA testmybrain TO fphsadm;
GRANT USAGE ON SCHEMA testmybrain TO fphsusr;
GRANT USAGE ON SCHEMA testmybrain TO fphsetl;


GRANT ALL ON ALL TABLES IN SCHEMA testmybrain TO fphs;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA testmybrain TO fphsusr;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA testmybrain TO fphsetl;
GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON ALL TABLES IN SCHEMA testmybrain TO fphsadm;

GRANT ALL ON ALL SEQUENCES IN SCHEMA testmybrain TO fphs;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA testmybrain TO fphsusr;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA testmybrain TO fphsetl;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA testmybrain TO fphsadm;


DO
$body$
BEGIN

IF EXISTS (
   SELECT *
   FROM   pg_catalog.pg_roles
   WHERE  rolname = 'fphsrailsapp') THEN

   GRANT USAGE ON SCHEMA testmybrain TO fphsrailsapp;
   GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA testmybrain TO fphsrailsapp;
   GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA testmybrain TO fphsrailsapp;
END IF;


END
$body$;
