REVOKE ALL ON SCHEMA sleep FROM fphs;
GRANT ALL ON SCHEMA sleep TO fphs;
GRANT USAGE ON SCHEMA sleep TO fphsadm;
GRANT USAGE ON SCHEMA sleep TO fphsusr;
GRANT USAGE ON SCHEMA sleep TO fphsetl;


GRANT ALL ON ALL TABLES IN SCHEMA sleep TO fphs;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA sleep TO fphsusr;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA sleep TO fphsetl;
GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON ALL TABLES IN SCHEMA sleep TO fphsadm;

GRANT ALL ON ALL SEQUENCES IN SCHEMA sleep TO fphs;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA sleep TO fphsusr;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA sleep TO fphsetl;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA sleep TO fphsadm;


DO
$body$
BEGIN

IF EXISTS (
   SELECT *
   FROM   pg_catalog.pg_roles
   WHERE  rolname = 'fphsrailsapp') THEN

   GRANT USAGE ON SCHEMA sleep TO fphsrailsapp;
   GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA sleep TO fphsrailsapp;
   GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA sleep TO fphsrailsapp;
END IF;


END
$body$;
