REVOKE ALL ON SCHEMA filestore_admin FROM fphs;
GRANT ALL ON SCHEMA filestore_admin TO fphs;
GRANT USAGE ON SCHEMA filestore_admin TO fphsadm;
GRANT USAGE ON SCHEMA filestore_admin TO fphsusr;
GRANT USAGE ON SCHEMA filestore_admin TO fphsetl;


GRANT ALL ON ALL TABLES IN SCHEMA filestore_admin TO fphs;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA filestore_admin TO fphsusr;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA filestore_admin TO fphsetl;
GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON ALL TABLES IN SCHEMA filestore_admin TO fphsadm;

GRANT ALL ON ALL SEQUENCES IN SCHEMA filestore_admin TO fphs;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA filestore_admin TO fphsusr;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA filestore_admin TO fphsetl;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA filestore_admin TO fphsadm;


DO
$body$
BEGIN

IF EXISTS (
   SELECT *
   FROM   pg_catalog.pg_roles
   WHERE  rolname = 'fphsrailsapp') THEN

   GRANT USAGE ON SCHEMA filestore_admin TO fphsrailsapp;
   GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA filestore_admin TO fphsrailsapp;
   GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA filestore_admin TO fphsrailsapp;
END IF;


END
$body$;

REVOKE ALL ON SCHEMA filestore FROM fphs;
GRANT ALL ON SCHEMA filestore TO fphs;
GRANT USAGE ON SCHEMA filestore TO fphsadm;
GRANT USAGE ON SCHEMA filestore TO fphsusr;
GRANT USAGE ON SCHEMA filestore TO fphsetl;


GRANT ALL ON ALL TABLES IN SCHEMA filestore TO fphs;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA filestore TO fphsusr;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA filestore TO fphsetl;
GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON ALL TABLES IN SCHEMA filestore TO fphsadm;

GRANT ALL ON ALL SEQUENCES IN SCHEMA filestore TO fphs;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA filestore TO fphsusr;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA filestore TO fphsetl;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA filestore TO fphsadm;


DO
$body$
BEGIN

IF EXISTS (
   SELECT *
   FROM   pg_catalog.pg_roles
   WHERE  rolname = 'fphsrailsapp') THEN

   GRANT USAGE ON SCHEMA filestore TO fphsrailsapp;
   GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA filestore TO fphsrailsapp;
   GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA filestore TO fphsrailsapp;
END IF;


END
$body$;
