REVOKE ALL ON SCHEMA ipa_staging FROM fphs;
GRANT ALL ON SCHEMA ipa_staging TO fphs;
GRANT ALL ON SCHEMA ipa_staging TO fphsadm;
GRANT ALL ON SCHEMA ipa_staging TO fphsusr;
GRANT ALL ON SCHEMA ipa_staging TO fphsetl;


GRANT ALL ON ALL TABLES IN SCHEMA ipa_staging TO fphs;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA ipa_staging TO fphsusr;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA ipa_staging TO fphsetl;
GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON ALL TABLES IN SCHEMA ipa_staging TO fphsadm;

GRANT ALL ON ALL SEQUENCES IN SCHEMA ipa_staging TO fphs;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA ipa_staging TO fphsusr;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA ipa_staging TO fphsetl;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA ipa_staging TO fphsadm;


DO
$body$
BEGIN

IF EXISTS (
   SELECT *
   FROM   pg_catalog.pg_roles
   WHERE  rolname = 'fphsrailsapp') THEN

   GRANT USAGE ON SCHEMA ipa_staging TO fphsrailsapp;
   GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA ipa_staging TO fphsrailsapp;
   GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA ipa_staging TO fphsrailsapp;
END IF;


END
$body$;
