_definitions:

  enabled_if: &enabled_if

    # if performed a phone screening no consent to continue, disable after 14 days
    not_all_not_interested:
      any:
        dynamic_model__ipa_ps_initial_screenings:
          select_is_good_time_to_speak: not interested
          select_may_i_begin: not interested
          select_still_interested: 'no'

      all_created_at:
        dynamic_model__ipa_ps_initial_screenings:
          created_at:
            condition: <
            value: -14 days

    # if recorded a withdraw activity, disable after 14 days
    not_all_withdraw:
      any:
        dynamic_model__ipa_withdrawals:
          select_subject_withdrew_reason: withdrew
          select_investigator_terminated:
            - yes - due to ae
            - yes - other reason
          lost_to_follow_up_no_yes: 'yes'
          no_longer_participating_no_yes: 'yes'
      all_created_at:
        dynamic_model__ipa_withdrawals:
          created_at:
            condition: <
            value: -14 days

    # if performed a screening follow up and not eligible, disable after 14 days
    not_all_ineligible:
      dynamic_model__ipa_screenings:
        eligible_for_study_blank_yes_no: 'no'
        created_at:
          condition: <
          value: -14 days

    # if performed a screening follow up and not interested in participating, disable after 14 days
    not_all_ps_followup_not_interested:
      dynamic_model__ipa_screenings:
        still_interested_blank_yes_no: 'no'
        created_at:
          condition: <
          value: -14 days

    # if an exit or lost to follow up before scheduled, disable after 14 days
    not_all_tracker_exits:
      activity_log__ipa_assignments:
        extra_log_type:
          - exit_opt_out
          - exit_l2fu
          # if the exit survey has been completed, do not disable after 14 days
          #- completed
        created_at:
          condition: <
          value: -14 days

  ref_filestore_container: &ref_filestore_container
    nfs_store__manage__container:
      from: this
      add: one_to_this
      view_as:
        edit: hide
        show: filestore
        new: not_embedded

  save_trigger:
    on_create_filestore_container: &create_filestore_container
      create_filestore_container:
        name: general files
        label: General Files
        create_with_role: nfs_store group 600



  any_exit_or_complete: &any_exit_or_complete
    any_exit_or_complete:
      any_exit: &any_exit
        any_tracker_exits: &any_tracker_exit
          activity_log__ipa_assignments:
            extra_log_type:
              - exit_opt_out
              - exit_l2fu
              - completed
        any_withdrawal: &any_withdrawal
          dynamic_model__ipa_withdrawals:
            no_longer_participating_no_yes: 'yes'
            lost_to_follow_up_no_yes: 'yes'
            select_subject_withdrew_reason: withdrew
            select_investigator_terminated:
              - yes - due to ae
              - yes - other reason

      all_completed: &all_completed
        activity_log__ipa_assignments:
          extra_log_type: completed
