REVOKE ALL ON SCHEMA tbs FROM fphs;
GRANT ALL ON SCHEMA tbs TO fphs;
GRANT USAGE ON SCHEMA tbs TO fphsadm;
GRANT USAGE ON SCHEMA tbs TO fphsusr;
GRANT USAGE ON SCHEMA tbs TO fphsetl;


GRANT ALL ON ALL TABLES IN SCHEMA tbs TO fphs;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA tbs TO fphsusr;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA tbs TO fphsetl;
GRANT SELECT,INSERT,DELETE,TRUNCATE,UPDATE ON ALL TABLES IN SCHEMA tbs TO fphsadm;

GRANT ALL ON ALL SEQUENCES IN SCHEMA tbs TO fphs;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA tbs TO fphsusr;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA tbs TO fphsetl;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA tbs TO fphsadm;


DO
$body$
BEGIN

IF EXISTS (
   SELECT *
   FROM   pg_catalog.pg_roles
   WHERE  rolname = 'fphsrailsapp') THEN

   GRANT USAGE ON SCHEMA tbs TO fphsrailsapp;
   GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA tbs TO fphsrailsapp;
   GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA tbs TO fphsrailsapp;
END IF;


END
$body$;
