---
app_type:
  id: 3
  name: ipa
  label: IPA
  disabled: 
  admin_id: 2
  created_at: 
  updated_at: 
  app_configurations:

  user_access_controls:
  - id: 1342
    user_id: 
    resource_type: table
    resource_name: dynamic_model__ipa_reimbursement_reqs
    options: ''
    access: create
    disabled: false
    admin_id: 21
    app_type_id: 3
    role_name: tracker
    created_at: '2019-09-18T18:27:50.006Z'
    updated_at: '2019-09-18T18:27:50.006Z'
    user_email: 
  associated_activity_logs: []
 
  associated_dynamic_models:
  - id: 522
    name: IPA Reimbursement Requests
    table_name: ipa_reimbursement_reqs
    schema_name: 
    primary_key_name: id
    foreign_key_name: master_id
    description: ''
    admin_id: 21
    disabled: false
    created_at: '2019-09-18T18:23:11.540Z'
    updated_at: '2019-09-18T18:23:11.540Z'
    position: 50
    category: ipa-records
    table_key_name: ''
    field_list: participant_requested_yes_no submission_date additional_notes
    result_order: ''
    options: ''
    user_email: 

  associated_external_identifiers: []
  associated_reports: []
  associated_general_selections: []
  associated_message_templates: []
  associated_config_libraries: []
  associated_protocols: []
  associated_sub_processes: []
  associated_protocol_events: []
  nfs_store_filters: []
