require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ManualInvestigationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ManualInvestigation. As you add validations to ManualInvestigation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ManualInvestigationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all manual_investigations as @manual_investigations" do
      manual_investigation = ManualInvestigation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:manual_investigations)).to eq([manual_investigation])
    end
  end

  describe "GET #show" do
    it "assigns the requested manual_investigation as @manual_investigation" do
      manual_investigation = ManualInvestigation.create! valid_attributes
      get :show, {:id => manual_investigation.to_param}, valid_session
      expect(assigns(:manual_investigation)).to eq(manual_investigation)
    end
  end

  describe "GET #new" do
    it "assigns a new manual_investigation as @manual_investigation" do
      get :new, {}, valid_session
      expect(assigns(:manual_investigation)).to be_a_new(ManualInvestigation)
    end
  end

  describe "GET #edit" do
    it "assigns the requested manual_investigation as @manual_investigation" do
      manual_investigation = ManualInvestigation.create! valid_attributes
      get :edit, {:id => manual_investigation.to_param}, valid_session
      expect(assigns(:manual_investigation)).to eq(manual_investigation)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ManualInvestigation" do
        expect {
          post :create, {:manual_investigation => valid_attributes}, valid_session
        }.to change(ManualInvestigation, :count).by(1)
      end

      it "assigns a newly created manual_investigation as @manual_investigation" do
        post :create, {:manual_investigation => valid_attributes}, valid_session
        expect(assigns(:manual_investigation)).to be_a(ManualInvestigation)
        expect(assigns(:manual_investigation)).to be_persisted
      end

      it "redirects to the created manual_investigation" do
        post :create, {:manual_investigation => valid_attributes}, valid_session
        expect(response).to redirect_to(ManualInvestigation.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved manual_investigation as @manual_investigation" do
        post :create, {:manual_investigation => invalid_attributes}, valid_session
        expect(assigns(:manual_investigation)).to be_a_new(ManualInvestigation)
      end

      it "re-renders the 'new' template" do
        post :create, {:manual_investigation => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manual_investigation" do
        manual_investigation = ManualInvestigation.create! valid_attributes
        put :update, {:id => manual_investigation.to_param, :manual_investigation => new_attributes}, valid_session
        manual_investigation.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested manual_investigation as @manual_investigation" do
        manual_investigation = ManualInvestigation.create! valid_attributes
        put :update, {:id => manual_investigation.to_param, :manual_investigation => valid_attributes}, valid_session
        expect(assigns(:manual_investigation)).to eq(manual_investigation)
      end

      it "redirects to the manual_investigation" do
        manual_investigation = ManualInvestigation.create! valid_attributes
        put :update, {:id => manual_investigation.to_param, :manual_investigation => valid_attributes}, valid_session
        expect(response).to redirect_to(manual_investigation)
      end
    end

    context "with invalid params" do
      it "assigns the manual_investigation as @manual_investigation" do
        manual_investigation = ManualInvestigation.create! valid_attributes
        put :update, {:id => manual_investigation.to_param, :manual_investigation => invalid_attributes}, valid_session
        expect(assigns(:manual_investigation)).to eq(manual_investigation)
      end

      it "re-renders the 'edit' template" do
        manual_investigation = ManualInvestigation.create! valid_attributes
        put :update, {:id => manual_investigation.to_param, :manual_investigation => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested manual_investigation" do
      manual_investigation = ManualInvestigation.create! valid_attributes
      expect {
        delete :destroy, {:id => manual_investigation.to_param}, valid_session
      }.to change(ManualInvestigation, :count).by(-1)
    end

    it "redirects to the manual_investigations list" do
      manual_investigation = ManualInvestigation.create! valid_attributes
      delete :destroy, {:id => manual_investigation.to_param}, valid_session
      expect(response).to redirect_to(manual_investigations_url)
    end
  end

end
