require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SubProcessesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SubProcess. As you add validations to SubProcess, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubProcessesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sub_processes as @sub_processes" do
      sub_process = SubProcess.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:sub_processes)).to eq([sub_process])
    end
  end

  describe "GET #show" do
    it "assigns the requested sub_process as @sub_process" do
      sub_process = SubProcess.create! valid_attributes
      get :show, {:id => sub_process.to_param}, valid_session
      expect(assigns(:sub_process)).to eq(sub_process)
    end
  end

  describe "GET #new" do
    it "assigns a new sub_process as @sub_process" do
      get :new, {}, valid_session
      expect(assigns(:sub_process)).to be_a_new(SubProcess)
    end
  end

  describe "GET #edit" do
    it "assigns the requested sub_process as @sub_process" do
      sub_process = SubProcess.create! valid_attributes
      get :edit, {:id => sub_process.to_param}, valid_session
      expect(assigns(:sub_process)).to eq(sub_process)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SubProcess" do
        expect {
          post :create, {:sub_process => valid_attributes}, valid_session
        }.to change(SubProcess, :count).by(1)
      end

      it "assigns a newly created sub_process as @sub_process" do
        post :create, {:sub_process => valid_attributes}, valid_session
        expect(assigns(:sub_process)).to be_a(SubProcess)
        expect(assigns(:sub_process)).to be_persisted
      end

      it "redirects to the created sub_process" do
        post :create, {:sub_process => valid_attributes}, valid_session
        expect(response).to redirect_to(SubProcess.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sub_process as @sub_process" do
        post :create, {:sub_process => invalid_attributes}, valid_session
        expect(assigns(:sub_process)).to be_a_new(SubProcess)
      end

      it "re-renders the 'new' template" do
        post :create, {:sub_process => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sub_process" do
        sub_process = SubProcess.create! valid_attributes
        put :update, {:id => sub_process.to_param, :sub_process => new_attributes}, valid_session
        sub_process.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested sub_process as @sub_process" do
        sub_process = SubProcess.create! valid_attributes
        put :update, {:id => sub_process.to_param, :sub_process => valid_attributes}, valid_session
        expect(assigns(:sub_process)).to eq(sub_process)
      end

      it "redirects to the sub_process" do
        sub_process = SubProcess.create! valid_attributes
        put :update, {:id => sub_process.to_param, :sub_process => valid_attributes}, valid_session
        expect(response).to redirect_to(sub_process)
      end
    end

    context "with invalid params" do
      it "assigns the sub_process as @sub_process" do
        sub_process = SubProcess.create! valid_attributes
        put :update, {:id => sub_process.to_param, :sub_process => invalid_attributes}, valid_session
        expect(assigns(:sub_process)).to eq(sub_process)
      end

      it "re-renders the 'edit' template" do
        sub_process = SubProcess.create! valid_attributes
        put :update, {:id => sub_process.to_param, :sub_process => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sub_process" do
      sub_process = SubProcess.create! valid_attributes
      expect {
        delete :destroy, {:id => sub_process.to_param}, valid_session
      }.to change(SubProcess, :count).by(-1)
    end

    it "redirects to the sub_processes list" do
      sub_process = SubProcess.create! valid_attributes
      delete :destroy, {:id => sub_process.to_param}, valid_session
      expect(response).to redirect_to(sub_processes_url)
    end
  end

end
