module Seeds
  module TermsOfUse

    NEW_USER_DEFAULT_TEMPLATE: string
    NEW_USER_GDPR_TEMPLATE: string
    UPDATE_USER_DEFAULT_TEMPLATE: string
    UPDATE_USER_GDPR_TEMPLATE: string

    def self.add_values: -> void

    def self.create_templates: -> void

    def self.do_last: -> bool

    def self.setup: -> void
  end
end
